version: 2.1

jobs:
  test:
    docker:
      - image: jonbaldie/queue
    steps:
      - run: cd /queue && deno test --allow-read --allow-write --allow-net

workflows:
  test:
    jobs:
      - test
