version: 2.1

jobs:
  test:
    docker:
      - image: denoland/deno:2.7.6
    steps:
      - run:
          name: Install git
          command: apt-get update -yqq && apt-get install -yqq git
      - run:
          name: Checkout code via HTTPS
          command: |
            git clone https://github.com/jonbaldie/queue.git .
            git checkout "${CIRCLE_SHA1}"
      - run:
          name: Build and run tests
          command: |
            touch persist.dat
            deno compile --allow-read --allow-write=./persist.dat --allow-net=0.0.0.0:3000 --allow-env=HOST,PORT,PERSIST,QUEUE_API_TOKEN main.ts
            deno test --allow-read --allow-write --allow-net --allow-env --allow-run

workflows:
  test:
    jobs:
      - test
